version: '3'

# to compile the services
# ./mvnw clean package -Dquarkus.container-image.build=true

volumes:
  db-data:

networks:
  mensa-db-network:
  mensa-event-network:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - mensa-event-network
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    networks:
      - mensa-event-network
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"

  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_DB: mensa
      POSTGRES_USER: mensa
      POSTGRES_PASSWORD: mensa
    networks:
      - mensa-db-network
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"

  email:
    image: mensa/email-service:1.0.0-SNAPSHOT
    depends_on:
      - db
      - kafka
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/mensa
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mensa-db-network
      - mensa-event-network
    ports:
      - 5001:5005
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"

  user:
    image: mensa/user-service:1.0.0-SNAPSHOT
    depends_on:
      - db
      - kafka
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/mensa
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mensa-db-network
      - mensa-event-network
    ports:
      - 8080:8080
      - 5002:5005
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"
