quarkus:
  datasource:
    db-kind: postgresql
    username: mensa
    password: mensa
    jdbc:
      url: jdbc:postgresql://db:5432/mensa
  flyway:
    migrate-at-start: true
    schemas: users
  hibernate-orm:
    database:
      default-schema: users
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "com.hillayes":
        level: DEBUG

mensa:
  events:
    group: user
