quarkus:
  datasource:
    db-kind: postgresql
    username: mensa
    password: mensa
    jdbc:
      url: jdbc:postgresql://db:5432/mensa
"%test":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:5432/mensa

  flyway:
    baseline-on-migrate: true
    migrate-at-start: true
    schemas: email

  hibernate-orm:
    database:
      default-schema: email

  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "com.hillayes":
        level: DEBUG

kafka:
  bootstrap:
    servers: kafka:9092


mensa:
  events:
    group: email

  emails:
    user-created:
      template: user-created.email
      sender: customer-care@mensa.co.uk
      subject: 'Complete your Mensa application'
    user-onboarded:
      template: user-onboarded.email
      sender: customer-care@mensa.co.uk
      subject: 'Welcome to Mensa'
